# Generated by Django 4.2.1 on 2023-06-13 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streetName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NeedHelp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('age', models.IntegerField()),
                ('reason', models.TextField()),
                ('streetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.street')),
            ],
        ),
    ]
